notifications:
  email: false
language: generic
sudo: required
addons:
  apt:
    packages:
      - clisp
install:
  - wget http://mr.gy/blog/clozure-cl_1.11_amd64.deb
  - sudo dpkg -i clozure-cl_1.11_amd64.deb
  - wget http://http.us.debian.org/debian/pool/main/s/sbcl/sbcl_1.3.14-2+b1_amd64.deb
  - sudo dpkg -i sbcl_1.3.14-2+b1_amd64.deb
script:
  - make all
