notifications:
  email: false
language: generic
sudo: required
addons:
  apt:
    packages:
      - clisp
      - sbcl
install:
  - wget http://mr.gy/blog/clozure-cl_1.11_amd64.deb
  - sudo dpkg -i clozure-cl_1.11_amd64.deb
script:
  - make all
