notifications:
  email: false
language: generic
addons:
  apt:
    packages:
      - clisp
      - sbcl
install:
  - wget http://mr.gy/blog/clozure-cl_1.11_amd64.deb
  - dpkg -i clozure-cl_1.11_amd64.deb
script:
  - make fetch
  - make
  - make test-all
